apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    link.argocd.argoproj.io/external-link: http://78.47.144.24:30829/
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
